#
# Copyright (c) 2023 by Delphix. All rights reserved.
#

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
      - id: isort

  - repo: https://github.com/jorgetomtz/pre-commit-hooks
    rev: v0.2.4
    hooks:
      - id: copyright-check
        args: ["-o", "Delphix"]
        exclude: >
          (?x)^(
            .*\.zip|
            .*__init__.py|
            .flake8|
            .*.pylintrc|
            .*.coveragerc|
            .*poetry.lock|
            .*.dockerignore|
            .*.mako|
          )$

  - repo: local
    hooks:
    - id: pytest-check-unload
      name: pytest-check-unload
      stages: [commit]
      types: [python]
      entry: unload-service/run_tests.sh
      language: script
      pass_filenames: false
      files: ^unload-service/.*.py

  - repo: local
    hooks:
      - id: pytest-check-load
        name: pytest-check-load
        stages: [ commit ]
        types: [ python ]
        entry: load-service/run_tests.sh
        language: script
        pass_filenames: false
        files: ^load-service/.*.py