#
# Copyright (c) 2023 by Delphix. All rights reserved.
#

"""create connector table

Revision ID: 9f11580e8d0e
Revises:
Create Date: 2023-07-13 15:46:16.381103

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.Text(length=25), nullable=False),
        sa.Column("password", sa.Text(length=25), nullable=False),
        sa.Column("jdbc_url", sa.Text(), nullable=False),
        sa.Column("certificate_key_file", sa.Text(), nullable=True),
        sa.Column("tls_ca_file", sa.Text(), nullable=True),
        sa.Column("ssl", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("connector")
    # ### end Alembic commands ###
